[build]
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/cookie-redirect"
  status = 200
  force = true
  conditions = { Cookie = ["i18n_redirected"] }

[[redirects]]
  from = "/"
  to = "/en"
  force = true
  status = 302
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/"
  to = "/es"
  force = true
  status = 302
  conditions = { Language = ["es"] }

[[redirects]]
  from = "/"
  to = "/fr"
  force = true
  status = 302
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
