name = "language-redirector"
type = "webpack"
account_id = "***REMOVED***"
workers_dev = true

[env.production]
route = "***REMOVED****"
zone_id = "***REMOVED***"

[site]
bucket = "./static-page"
entry-point = "./workers-site"
